spring.application.name=criptovision-api

# Configurações de Conexão com o MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/criptovision?serverTimezone=UTC
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurações do Hibernate/JPA
# Mostra no console os comandos SQL que o Spring vai gerar sozinho
spring.jpa.show-sql=true
# Atualiza o banco automaticamente baseado no código Java
spring.jpa.hibernate.ddl-auto=update
