name: Testes do backend

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

jobs:
  testes:
    name: Testes com Maven
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Baixar o código
        uses: actions/checkout@v6

      - name: Configurar Java 25
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "25"
          cache: maven

      - name: Permitir execução do Maven Wrapper
        run: chmod +x mvnw

      - name: Executar os testes
        run: ./mvnw --batch-mode --no-transfer-progress clean test
